# Configuration for GitHub PR Labeler
# https://github.com/actions/labeler

docs:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md"]

tests:
  - changed-files:
      - any-glob-to-any-file: ["**/*.test.ts"]

"github actions":
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
